# General
set -g default-terminal "xterm-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"
set -g set-clipboard on
set -g history-limit 10000

# Automatically set window title
set-window-option -g automatic-rename on
set-option -g set-titles on

# Unbinds
unbind C-b	# orignal prefix
unbind n    # next-window
unbind p    # previous-window
unbind &    # kill-window

# New Prefix (Alt+1)
set -g prefix M-1

# Windows
bind -n M-/ new-window
bind -n M-right next
bind -n M-left prev
bind -n M-e split-window -h -c "#{pane_current_path}"
bind -n M-w split-window -v -c "#{pane_current_path}"

# Panes
bind -n M-a select-pane -t :.-
bind -n M-d select-pane -t :.+
bind -n M-> swap-pane -D
bind -n M-< swap-pane -U       
bind -n M-q kill-pane


# Set bind key to reload configuration file
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# Enable mouse support
set -g mouse on

# Weather config
set-option -g @tmux-weather-format "%t"

####
# Remote
bind -T root -n 'M-\' \
    set prefix None \;\
    set key-table off \;\
    if -F '#{pane_in_mode}' 'send-keys -X cancel' \;\
    refresh-client -S \;\

bind -T off -n 'M-\' \
  set -u prefix \;\
  set -u key-table \;\
  refresh-client -S

# Nova Theme
set -g @nova-rows 0
set -g @nova-nerdfonts true
set -g @nova-nerdfonts-left 
set -g @nova-nerdfonts-right 

set -g @nova-pane "#I#{?pane_in_mode,  #{pane_mode},}  #W"

set -g @nova-segment-mode "#{?client_prefix,Ω,α}"
set -g @nova-segment-mode-colors "#{?#{==:#{prefix},None},#ff5555,#50fa7b} #282a36"

set -g "@nova-status-style-bg" "#282a36"
set -g "@nova-status-style-fg" "#f8f8f2"
set -g "@nova-status-style-active-bg" "#{?#{==:#W,ssh},#ff5555,#3399FF}"
set -g "@nova-status-style-active-fg" "#f8f8f2"

set -g @nova-segment-spotify " #{spotify_info}"
set -g @nova-segment-spotify-colors "#3399FF, #f8f8f2"

set -g @cpu_percentage_format "%1.1f%%"
set -g @nova-segment-cpu "CPU: #{cpu_percentage}"
set -g @nova-segment-cpu-colors "#1B0F22 #f8f8f2"

set -g @nova-segment-mem "RAM: #{ram_percentage}"
set -g @nova-segment-mem-colors "#282a36 #f8f8f2"

set -g @nova-segment-weather "#{weather}"
set -g @nova-segment-weather-colors "#1B0F22 #f8f8f2"

set -g @nova-segment-date "%a %b %d"
set -g @nova-segment-date-colors "#282a36 #f8f8f2"

set -g @nova-segment-clock "%H:%M"
set -g @nova-segment-clock-colors "#1B0F22 #f8f8f2"

set -g @nova-segment-whoami "#(whoami)@#h"
set -g @nova-segment-whoami-colors "#3399FF #f8f8f2"

set -g @nova-segment-end "#()"
set -g @nova-segment-end-colors "#ff5555 #ff5555"

set -g @nova-segments-0-left "mode"
set -g @nova-segments-0-right "spotify cpu mem weather date clock whoami end"

set -g status-right-length 500
set -g status-left-length 100

# List of plugins 
# Install: shift + i
# Uninstall: alt + u
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'o0th/tmux-nova'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'xamut/tmux-weather'
set -g @plugin 'feqzz/tmux-spotify-info'
set -g @plugin 'tmux-plugins/tmux-logging' # shift + p

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'