# General
set -g default-terminal "screen-256color"
set -g history-limit 10000
set -sg repeat-time 600
set -s focus-events on
set -s escape-time 10

# Automatically set window title
set-window-option -g automatic-rename on
set-option -g set-titles on

# Unbinds
unbind C-b	# orignal prefix
unbind n    # next-window
unbind p    # previous-window
unbind &    # kill-window

# New Prefix (Alt+1)
set -g prefix M-1

# New bindings
bind -n M-a select-pane -t :.-
bind -n M-d select-pane -t :.+
#bind -n M-Left switch-client -p
#bind -n M-Right switch-client -n
bind -n M-, previous-window
bind -n M-. next-window
bind -n M-q kill-pane
bind -n M-k kill-window
bind -n M-e split-window -h -c "#{pane_current_path}"
bind -n M-w split-window -v -c "#{pane_current_path}"
bind -n M-> swap-pane -D
bind -n M-< swap-pane -U       
#bind q kill-session
bind q kill-window

# Set bind key to reload configuration file
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# Enable mouse support
set -g mouse on

# Weather config
set-option -g @tmux-weather-location "Imst"
set-option -g @tmux-weather-format "%t"

####
# Remote
bind -T root F12  \
    set prefix None \;\
    set key-table off \;\
    set window-status-current-format "#[fg=black,bg=orange,nobold,noitalics,nounderscore] #[fg=black,bg=orange]#H #[fg=orange,bg=black,nobold,noitalics,nounderscore]#[fg=black,bg=red,nobold,noitalics,nounderscore]#[fg=black,bg=red] SSH Mode #[fg=red,bg=black,nobold,noitalics,nounderscore]" \;\
    if -F '#{pane_in_mode}' 'send-keys -X cancel' \;\
    refresh-client -S \;\

bind -T off F12 \
  set -u prefix \;\
  set -u key-table \;\
  set -u window-status-current-format \;\
  refresh-client -S
  
# Nord Theme
set -g @nord_tmux_show_status_content "0" # Disable default statusbar
set -g status-left "#[fg=black,bg=blue,bold] #S #[fg=blue,bg=black,nobold,noitalics,nounderscore]"
set -g window-status-current-format "#[fg=black,bg=cyan,nobold,noitalics,nounderscore] #H #[fg=cyan,bg=black,nobold,noitalics,nounderscore]#[fg=black,bg=cyan,nobold,noitalics,nounderscore] #[fg=black,bg=cyan]#W #F #[fg=cyan,bg=black,nobold,noitalics,nounderscore]"

set -g status-right "#{spotify_info} "
set -ga status-right "#{prefix_highlight}"
set -ga status-right "#[fg=brightblack,bg=black,nobold,noitalics,nounderscore]"
set -ga status-right "#[fg=white,bg=brightblack] #{weather} "
set -ga status-right "#[fg=white,bg=brightblack,nobold,noitalics,nounderscore]"
set -ga status-right "#[fg=white,bg=brightblack] #{sysstat_cpu}"
set -ga status-right "#[fg=white,bg=brightblack,nobold,noitalics,nounderscore] "
set -ga status-right "#[fg=white,bg=brightblack] #{sysstat_mem}"
set -ga status-right "#[fg=white,bg=brightblack,nobold,noitalics,nounderscore] "
set -ga status-right "#[fg=white,bg=brightblack] %a %b %d "
set -ga status-right "#[fg=cyan,bg=brightblack,nobold,noitalics,nounderscore]"
set -ga status-right "#[fg=black,bg=cyan,bold] %H:%M "
set -ga status-right "#[fg=black,bg=cyan,bold] "
set -g status-right-length 500

# List of plugins 
# Install: shift + i
# Uninstall: alt + u
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'arcticicestudio/nord-tmux'
set -g @plugin 'samoshkin/tmux-plugin-sysstat'
set -g @plugin 'xamut/tmux-weather'
set -g @plugin 'feqzz/tmux-spotify-info'
set -g @plugin 'tmux-plugins/tmux-logging' # shift + p

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'