# Browser tab right
# gesture swipe left 4 ydotool key 29:1 109:1 109:0 29:0 # ctrl+pagedown

# Browser tab left
# gesture swipe right	4 ydotool key 29:1 104:1 104:0 29:0 # ctrl+pageup

# Browser go forward (works only for Xorg, and Xwayland clients)
# gesture swipe down 4 ydotool key 56:1 105:1 105:0 56:0 # alt+Left

# Browser go back (works only for Xorg, and Xwayland clients)
# gesture swipe up 4 ydotool key 56:1 106:1 106:0 56:0 # alt+Right 

# Close Window
# gesture swipe down 3 ydotool key 29:1 17:1 17:0 29:0 # ctrl+w

gesture swipe left 4 xdotool key ctrl+Page_Down
gesture swipe right	4 xdotool key ctrl+Page_Up
gesture swipe down 4 xdotool key alt+Left
gesture swipe up 4 xdotool key alt+Right 
gesture swipe down 3 xdotool key ctrl+w

# ydotool
# CTRL ALT 29 56
# LEFT RIGHT 105 106
# PAGE UP / DOWN 104 109
# W 17