-- Main
require "user.utils"
require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.theme"

-- Plugin Configs
require "configs.alpha"
require "configs.treesitter"
require "configs.telescope"
require "configs.bufferline"
require "configs.lualine"
require "configs.toggleterm"
require "configs.indent-line"
require "configs.cinnamon"
require "configs.gitsigns"
require "configs.colorizer"
require "configs.which-key"
require "configs.autopairs"
require "configs.textcase"
require "configs.trouble"
require "configs.null-ls"
require "configs.lsp"
require "configs.cmp"
require "configs.go"
